### ISSUE TITLE
Set operations on periods

### ISSUE THREAD

**Issue by brentgreeff** [billaul/active_period#2]
Awesome gem, but I wish it did a little more :)

Specifically 

```ruby
Period.new('1/01/2020'...'10/01/2020') & Period.new('9/01/2020'...'12/01/2020')

=> Period.new('9/01/2020'...'10/01/2020')
```

I can do:

```ruby
x.to_a & y.to_a
```

This is cool:
```ruby
@books = Book.where(published: Period.bounded(params[:from]..params[:to]))
```

but I would like to do the same intersection calculation, something like:

```ruby
@books = Book.intersection(:start_at, :end_at,  Period.bounded(params[:from]..params[:to]))
```

**Comment by billaul** [comment]
Interesting idea. 
Classic Range dont support `&` and `|` but i see the point

So `&` and also `|` will certainly be part of the next update.  
And, as there is no such things as an `empty Period`, if there is no overlap the return value will be `nil`

-----------
About the `intersection` . What you have in mind is something like this right ? 
```rb
Book.intersection(:start_at, :end_at,  Period.bounded(params[:from]..params[:to]))
# Is like 
period = Period.bounded(params[:from]..params[:to])
Book.where(start_at: period).or(Book.where(end_at: period))
```
If so, then intersection would be something to add to the ActiveRecord scope
